# generated by datamodel-codegen:
#   filename:  auth_data.yaml
#   timestamp: 2024-06-01T22:41:25+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class AuthenticationData(BaseModel):
    type: Optional[str] = Field(
        None,
        description="The authentication type that the client is attempting to complete.\nMay be omitted if `session` is given, and the client is reissuing a\nrequest which it believes has been completed out-of-band (for example,\nvia the [fallback mechanism](#fallback)).",
    )
    session: Optional[str] = Field(
        None, description="The value of the session key given by the homeserver."
    )
