# generated by datamodel-codegen:
#   filename:  client_device.yaml
#   timestamp: 2024-06-01T22:41:27+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Device(BaseModel):
    device_id: str = Field(
        ..., description="Identifier of this device.", examples=["QBUAZIFURK"]
    )
    display_name: Optional[str] = Field(
        None,
        description="Display name set by the user for this device. Absent if no name has been\nset.",
        examples=["android"],
    )
    last_seen_ip: Optional[str] = Field(
        None,
        description="The IP address where this device was last seen. (May be a few minutes out\nof date, for efficiency reasons).",
        examples=["1.2.3.4"],
    )
    last_seen_ts: Optional[int] = Field(
        None,
        description="The timestamp (in milliseconds since the unix epoch) when this devices\nwas last seen. (May be a few minutes out of date, for efficiency\nreasons).",
        examples=[1474491775024],
    )
