# generated by datamodel-codegen:
#   filename:  event_batch.yaml
#   timestamp: 2024-06-01T22:41:29+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Event(BaseModel):
    content: Dict[str, Any] = Field(
        ...,
        description="The fields in this object will vary depending on the type of event. When interacting with the REST API, this is the HTTP body.",
    )
    type: str = Field(
        ...,
        description="The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. 'com.example.subdomain.event.type'",
    )


class EventBatch(BaseModel):
    events: Optional[List[Event]] = Field(None, description="List of events.")
