# generated by datamodel-codegen:
#   filename:  m.login.terms_params.yaml
#   timestamp: 2024-06-01T22:41:32+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Field


class Policies(BaseModel):
    version: str = Field(
        ...,
        description="The version of this policy document. This is provided as a convenience for the client,\nand uses the [Opaque Identifier Grammar](/appendices/#opaque-identifiers).\n",
    )


class MLoginTermsParams(BaseModel):
    policies: Dict[str, Policies] = Field(
        ...,
        description='A map from "Policy ID" to the current definition of this policy document. The Policy ID is a unique\nidentifier for a given policy document, using the [Opaque Identifier Grammar](/appendices/#opaque-identifiers).\n',
    )
