# generated by datamodel-codegen:
#   filename:  m.mentions.yaml
#   timestamp: 2024-06-01T22:41:33+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class MMentions(BaseModel):
    user_ids: Optional[List[str]] = Field(
        None, description="A list of Matrix IDs of mentioned users."
    )
    room: Optional[bool] = Field(
        None,
        description="A boolean set to `true` to mention the room, for an `@room` notification.\n(`room` should otherwise not be included on the event.)",
    )
