# generated by datamodel-codegen:
#   filename:  m.relates_to.yaml
#   timestamp: 2024-06-01T22:41:33+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class MRelatesTo(BaseModel):
    rel_type: str = Field(
        ...,
        description='The namespaced relationship type. Values must use the\n[Common Namespaced Identifier Grammar](/appendices/#common-namespaced-identifier-grammar).\n\nThe relationship type determines how clients should perceive the event, and in what\ncontext. Some relationship types are processed server-side for "bundling", though not\nall relationships require such behaviour. For example, an [`m.thread` relationship type](/client-server-api/#threading)\ndenotes that the event is part of a "thread" of messages and should be rendered as\nsuch.',
    )
    event_id: str = Field(
        ..., description="The event ID of the event that this event relates to."
    )
