# generated by datamodel-codegen:
#   filename:  openid_token.yaml
#   timestamp: 2024-06-01T22:41:35+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class OpenIdCredentials(BaseModel):
    access_token: str = Field(
        ...,
        description="An access token the consumer may use to verify the identity of\nthe person who generated the token. This is given to the federation\nAPI `GET /openid/userinfo` to verify the user's identity.",
    )
    token_type: str = Field(..., description="The string `Bearer`.")
    matrix_server_name: str = Field(
        ...,
        description="The homeserver domain the consumer should use when attempting to\nverify the user's identity.",
    )
    expires_in: int = Field(
        ...,
        description="The number of seconds before this token expires and a new one must\nbe generated.",
    )
