# generated by datamodel-codegen:
#   filename:  public_rooms_response.yaml
#   timestamp: 2024-06-01T22:41:36+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .public_rooms_chunk import PublicRoomsChunk


class PublicRoomsResponse(BaseModel):
    chunk: List[PublicRoomsChunk] = Field(
        ...,
        description="A paginated chunk of public rooms.",
    )
    next_batch: Optional[str] = Field(
        None,
        description="A pagination token for the response. The absence of this token\nmeans there are no more results to fetch and the client should\nstop paginating.",
    )
    prev_batch: Optional[str] = Field(
        None,
        description="A pagination token that allows fetching previous results. The\nabsence of this token means there are no results before this\nbatch, i.e. this is the first batch.",
    )
    total_room_count_estimate: Optional[int] = Field(
        None,
        description="An estimate on the total number of public rooms, if the\nserver has an estimate.",
    )
