# generated by datamodel-codegen:
#   filename:  push_rule.yaml
#   timestamp: 2024-06-01T22:41:37+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class PushCondition(BaseModel):
    kind: str = Field(
        ...,
        description="The kind of condition to apply. See [conditions](/client-server-api/#conditions) for\nmore information on the allowed kinds and how they work.",
    )
    key: Optional[str] = Field(
        None,
        description="Required for `event_match`, `event_property_is` and `event_property_contains`\nconditions. The dot-separated field of the event to match.\n\nRequired for `sender_notification_permission` conditions. The field in\nthe power level event the user needs a minimum power level for. Fields\nmust be specified under the `notifications` property in the power level\nevent's `content`.",
        examples=["content.body"],
    )
    pattern: Optional[str] = Field(
        None,
        description="Required for `event_match` conditions. The [glob-style pattern](/appendices#glob-style-matching)\nto match against.",
    )
    is_: Optional[str] = Field(
        None,
        alias="is",
        description="Required for `room_member_count` conditions. A decimal integer\noptionally prefixed by one of, ==, <, >, >= or <=. A prefix of < matches\nrooms where the member count is strictly less than the given number and\nso forth. If no prefix is present, this parameter defaults to ==.",
    )
    value: Optional[Union[str, int, bool]] = Field(
        None,
        description="Required for `event_property_is` and `event_property_contains` conditions.\nA non-compound [canonical JSON](/appendices#canonical-json) value to match\nagainst.",
    )


class PushRule(BaseModel):
    actions: List[Union[str, Dict[str, Any]]] = Field(
        ..., description="The actions to perform when this rule is matched."
    )
    default: bool = Field(
        ..., description="Whether this is a default rule, or has been set explicitly."
    )
    enabled: bool = Field(..., description="Whether the push rule is enabled or not.")
    rule_id: str = Field(..., description="The ID of this rule.")
    conditions: Optional[List[PushCondition]] = Field(
        None,
        description="The conditions that must hold true for an event in order for a rule to be\napplied to an event. A rule with no conditions always matches. Only\napplicable to `underride` and `override` rules.",
    )
    pattern: Optional[str] = Field(
        None,
        description="The [glob-style pattern](/appendices#glob-style-matching) to match against.\nOnly applicable to `content` rules.",
    )
