# generated by datamodel-codegen:
#   filename:  room_event_filter.yaml
#   timestamp: 2024-06-01T22:41:40+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class EventFilter(BaseModel):
    limit: Optional[int] = Field(
        None,
        description="The maximum number of events to return, must be an integer greater than 0.\n\nServers should apply a default value, and impose a maximum value to avoid\nresource exhaustion.\n",
    )
    not_senders: Optional[List[str]] = Field(
        None,
        description="A list of sender IDs to exclude. If this list is absent then no senders are excluded. A matching sender will be excluded even if it is listed in the `'senders'` filter.",
    )
    not_types: Optional[List[str]] = Field(
        None,
        description="A list of event types to exclude. If this list is absent then no event types are excluded. A matching type will be excluded even if it is listed in the `'types'` filter. A '*' can be used as a wildcard to match any sequence of characters.",
    )
    senders: Optional[List[str]] = Field(
        None,
        description="A list of senders IDs to include. If this list is absent then all senders are included.",
    )
    types: Optional[List[str]] = Field(
        None,
        description="A list of event types to include. If this list is absent then all event types are included. A `'*'` can be used as a wildcard to match any sequence of characters.",
    )


class Model(EventFilter):
    unread_thread_notifications: Optional[bool] = Field(
        None,
        description="If `true`, enables per-[thread](/client-server-api/#threading) notification\ncounts. Only applies to the `/sync` endpoint. Defaults to `false`.",
    )
    lazy_load_members: Optional[bool] = Field(
        None,
        description="If `true`, enables lazy-loading of membership events. See\n[Lazy-loading room members](/client-server-api/#lazy-loading-room-members)\nfor more information. Defaults to `false`.",
    )
    include_redundant_members: Optional[bool] = Field(
        None,
        description="If `true`, sends all membership events for all events, even if they have already\nbeen sent to the client. Does not\napply unless `lazy_load_members` is `true`. See\n[Lazy-loading room members](/client-server-api/#lazy-loading-room-members)\nfor more information. Defaults to `false`.",
    )
    not_rooms: Optional[List[str]] = Field(
        None,
        description="A list of room IDs to exclude. If this list is absent then no rooms are excluded. A matching room will be excluded even if it is listed in the `'rooms'` filter.",
    )
    rooms: Optional[List[str]] = Field(
        None,
        description="A list of room IDs to include. If this list is absent then all rooms are included.",
    )
    contains_url: Optional[bool] = Field(
        None,
        description="If `true`, includes only events with a `url` key in their content. If `false`, excludes those events. If omitted, `url` key is not considered for filtering.",
    )
