# generated by datamodel-codegen:
#   filename:  security.yaml
#   timestamp: 2024-06-01T22:41:41+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any
