# generated by datamodel-codegen:
#   filename:  tag.yaml
#   timestamp: 2024-06-01T22:41:43+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Tag(BaseModel):
    order: Optional[float] = Field(
        None,
        description="A number in a range `[0,1]` describing a relative\nposition of the room under the given tag.",
        examples=[0.25],
    )
