# generated by datamodel-codegen:
#   filename:  third_party_signed.yaml
#   timestamp: 2024-06-01T22:41:44+00:00

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Field


class ThirdPartySigned(BaseModel):
    sender: str = Field(
        ...,
        description="The Matrix ID of the user who issued the invite.",
        examples=["@alice:example.org"],
    )
    mxid: str = Field(
        ..., description="The Matrix ID of the invitee.", examples=["@bob:example.org"]
    )
    token: str = Field(
        ...,
        description="The state key of the m.third_party_invite event.",
        examples=["random8nonce"],
    )
    signatures: Dict[str, Dict[str, str]] = Field(
        ...,
        description="A signatures object containing a signature of the entire signed object.",
        examples=[{"example.org": {"ed25519:0": "some9signature"}}],
        title="Signatures",
    )
