# generated by datamodel-codegen:
#   filename:  full.yaml
#   timestamp: 2024-06-01T22:41:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import Homeserver, IdentityServer


class Discovery(BaseModel):
    m_homeserver: Homeserver = Field(..., alias="m.homeserver")
    m_identity_server: Optional[IdentityServer] = Field(None, alias="m.identity_server")
