# generated by datamodel-codegen:
#   filename:  full.yaml
#   timestamp: 2024-06-01T22:41:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import AnyUrl, BaseModel, Field


class Homeserver(BaseModel):
    base_url: AnyUrl = Field(
        ...,
        description="The base URL for the homeserver for client-server connections.",
        examples=["https://matrix.example.com"],
    )


class IdentityServer(BaseModel):
    base_url: AnyUrl = Field(
        ...,
        description="The base URL for the identity server for client-server connections.",
        examples=["https://identity.example.com"],
    )


class DiscoveryInformation(BaseModel):
    m_homeserver: Homeserver = Field(..., alias="m.homeserver")
    m_identity_server: Optional[IdentityServer] = Field(None, alias="m.identity_server")
