# generated by datamodel-codegen:
#   filename:  homeserver.yaml
#   timestamp: 2024-06-01T22:41:47+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field


class HomeserverInformation(BaseModel):
    base_url: AnyUrl = Field(
        ...,
        description="The base URL for the homeserver for client-server connections.",
        examples=["https://matrix.example.com"],
    )
