# generated by datamodel-codegen:
#   filename:  rate_limited.yaml
#   timestamp: 2024-06-01T22:41:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Error(BaseModel):
    errcode: str = Field(..., description="An error code.", examples=["M_UNKNOWN"])
    error: Optional[str] = Field(
        None,
        description="A human-readable error message.",
        examples=["An unknown error occurred"],
    )


class Model(Error):
    errcode: str = Field(
        ...,
        description="The M_LIMIT_EXCEEDED error code",
        examples=["M_LIMIT_EXCEEDED"],
    )
    error: Optional[str] = Field(
        None,
        description="A human-readable error message.",
        examples=["Too many requests"],
    )
    retry_after_ms: Optional[int] = Field(
        None,
        description="The amount of time in milliseconds the client should wait\nbefore trying the request again.",
        examples=[2000],
    )
