# generated by datamodel-codegen:
#   filename:  one_time_keys.yaml
#   timestamp: 2024-06-01T22:41:34+00:00

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, Field, RootModel, constr


class OneTimeKeys1(BaseModel):
    key: str = Field(..., description="The key, encoded using unpadded base64.")
    signatures: Dict[constr(pattern=r"^@"), Dict[str, Any]] = Field(
        ...,
        description="Signature for the device. Mapped from user ID to signature object,\ncontaining mapping from _key signing identifier_ to the signature\n(see also: [Signing JSON](/appendices/#signing-json))",
    )


class OneTimeKeys(RootModel[Optional[Dict[str, Union[str, OneTimeKeys1]]]]):
    root: Optional[Dict[str, Union[str, OneTimeKeys1]]] = None
