# generated by datamodel-codegen:
#   filename:  user_identifier.yaml
#   timestamp: 2024-06-01T22:41:45+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class UserIdentifier(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str = Field(
        ...,
        description="The type of identification.  See [Identifier types](/client-server-api/#identifier-types) for supported values and additional property descriptions.",
    )
