name: Build Status

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Lint with Black
        run: |
          pip install black
          black --check .
      - name: Lint with isort
        run: |
          pip install isort
          isort --check --profile=black .

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          wget https://gitlab.matrix.org/matrix-org/olm/-/archive/master/olm-master.tar.bz2
          tar -xvf olm-master.tar.bz2
          pushd olm-master && make && sudo make PREFIX="/usr" install && popd
          rm -r olm-master
          pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.11 ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: |
          wget https://gitlab.matrix.org/matrix-org/olm/-/archive/master/olm-master.tar.bz2
          tar -xvf olm-master.tar.bz2
          pushd olm-master && make && sudo make PREFIX="/usr" install && popd
          rm -r olm-master
          pip install tox
      - name: Run Tox
        run: tox -e coverage
